#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -std=gnu89 -fPIC -w"
export CXXFLAGS="$CXXFLAGS -fPIC -w"

# fix parallel builds
sed -e 's/ECHO_XE/ECHOGS_XE/g' \
	-e 's/^\($(GLOBJ)md5.$(OBJ) :.*\)/\1 $(ECHOGS_XE)/' \
	base/lib.mak > _
mv -f _ base/lib.mak

rm -rf cups expat jbig2dec jpeg lcms2mt libpng openjpeg tesseract tiff zlib

./configure \
    --prefix=/usr \
    --disable-gtk \
    --disable-dbus \
    --without-libpaper \
    --without-tesseract \
    --with-drivers=ALL \
    --with-fontpaths=/usr/share/ghostscript/fonts/:/usr/share/fonts

make so all
make -j1 install-so install

rm -rf "$1/usr/share/man/de/"
