#!/bin/sh -e

export DESTDIR="$1"

export CFLAGS="$CFLAGS -std=c17 -w"
export CXXFLAGS="$CXXFLAGS -w"

rm -rf cups expat jbig2dec jpeg lcms2mt libpng openjpeg tesseract tiff zlib 

sed "s/gscms_transformm_color_const/gscms_transform_color_const/" \
    base/gsicc_lcms2.c > _
mv -f _ base/gsicc_lcms2.c

./configure \
    --prefix=/usr \
    --disable-gtk \
    --disable-dbus \
    --with-drivers=ALL \
    --with-fontpaths=/usr/share/ghostscript/fonts/:/usr/share/fonts

make so all
make -j1 install-so install

rm -rf "$1/usr/share/man/de/"
