#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_C_FLAGS:STRING="$CFLAGS" \
    -DCMAKE_BUILD_TYPE:STRING=None \
    -DGRAPHITE2_COMPARE_RENDERER=OFF \
    -DGRAPHITE2_NFILEFACE=ON

cmake --build   build
cmake --install build
