#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=/usr/lib \
    -DENABLE_BOOST=OFF \
    -DENABLE_CPP=ON \
    -DENABLE_QT5=OFF \
    -DENABLE_QT6=OFF \
    -DENABLE_GPGME=OFF \
    -DWITH_NSS3=OFF \
    -DENABLE_UNSTABLE_API_ABI_HEADERS=ON \
    -DBUILD_CPP_TESTS=OFF \
    -DBUILD_MANUAL_TESTS=OFF

cmake --build   build
cmake --install build
