#!/bin/sh -e

mkdir -p "$1"/usr/share
mkdir -p pkgs-packed
mkdir -p pkgs-unpacked

(
    cd pkgs-packed
    unzip ../texlive-core-*-src.zip?no-extract > /dev/null
)

(
    cd pkgs-unpacked
    find ../pkgs-packed -name '*.tar.xz' -exec tar -xf {} \;
    find . -maxdepth 1 -name 'texmf*' -exec mv {} "$1"/usr/share/ \;
    find . -type d -mindepth 1 -exec mkdir -p "$1"/usr/share/texmf-dist/{} \;
    find . -type f -exec mv {} "$1"/usr/share/texmf-dist/{} \;
)

# Fix paths
# Intended behavior.
# shellcheck disable=2016
sed -e 's:^\(TEXMFROOT *= *\)$SELFAUTOPARENT$:\1/usr/share:g' \
    "$1"/usr/share/texmf-dist/web2c/texmf.cnf > _
mv -f _ "$1"/usr/share/texmf-dist/web2c/texmf.cnf

# Intended behavior.
# shellcheck disable=2016
for f in \
    "$1"/usr/share/texmf-dist/scripts/texlive/updmap.pl \
    "$1"/usr/share/texmf-dist/scripts/texlive/fmtutil.pl; do
    sed -e 's:\$TEXMFROOT/tlpkg:\$TEXMFROOT/texmf-dist/tlpkg:g' "$f" > _
    mv -f _ "$f"
    chmod +x "$f"
done

rm -rf pkgs-packed pkgs-unpacked
