#!/bin/sh -e

# This hook is meant to supplement the
# [kiss-tex](https://github.com/ehawkvu/kiss-tex)
# repo. It contains workarounds for certain packages.

case "$1" in
    pre-build)
        case "$2" in
            # If we are missing any of the dependencies in the 'base' version
            # of freetype-harfbuzz, then fail.
            # This is so that wayland people can also use this package without
            # having to fork.
            freetype-harfbuzz)
                diff "$(kiss search "$2" | sed -n "2p")/depends" \
                     "$(kiss search "$2" | sed -n "1p")/depends" |
                     awk '/</{if (0 != system("kiss list " $2)){exit 1}}'
                ;;
        esac
        ;;
esac
