#!/bin/sh -e

cat << EOF
#########################################################################
#                                                                       #
# To build TeXLive, you'll need to run the following command:           #
#                                                                       #
# $ kiss a | grep graphite-harfbuzz | kiss a -                          #
#                                                                       #
#########################################################################
EOF
