#!/bin/sh -e

cat << EOF | ed zzip/CMakeLists.txt
289,357s/bash -c/sh -c
203,243s/\${BASH}/sh/g
38,41d
w
q
EOF

cat << EOF | ed docs/CMakeLists.txt
105,117s/\${MV}/mv/g
122,152s/\${BASH}/sh/g
25d
w
q
EOF

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True \
    -DBUILD_STATIC_LIBS=False \
    -DBUILD_TESTS=OFF \
    -DMSVC_STATIC_RUNTIME=OFF \
    -DZZIPSDL=OFF \
    -DZZIPTEST=OFF \
    -DZZIPWRAP=OFF

cmake --build   build
cmake --install build
