#!/bin/sh -e

export DESTDIR="$1"

cmake -B build \
    -DCMAKE_BUILD_TYPE=None \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib \
    -DBUILD_SHARED_LIBS=True \
    -DBUILD_STATIC_LIBS=False \
    -DBUILD_TESTS=OFF \
    -DMSVC_STATIC_RUNTIME=OFF \
    -DZZIPSDL=OFF \
    -DZZIPTEST=OFF \
    -DZZIPWRAP=OFF

cmake --build   build
cmake --install build
