#!/bin/sh -e

echo " --> updmap-sys --syncwithtrees"
yes | updmap-sys --syncwithtrees
echo " --> updmap-sys"
updmap-sys
echo " --> mktexlsr"
mktexlsr
echo " --> texhash"
texhash
echo " --> fmtutil-sys --all"
fmtutil-sys --all
echo " --> mktexmf --all"
mktexmf --all
exit 0
